apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-service

  template:
    metadata:
      labels:
        app: demo-service

      # ðŸ”¥ THIS TRIGGERS AUTO RESTART
      annotations:
        config-version: "3"

    spec:
      containers:
        - name: demo-service
          image: argo-springboot:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: demo-config
